modern-js-dev/electron-sprout

apps/test-modern-electron/src/main/App.tsx, apps/test-modern-electron/typings/index.d.ts, packages/electron-plugin/global.d.ts
=> fix: some types define problem

apps/test-modern-electron/CHANGELOG.md, apps/test-modern-electron/package.json, packages/electron-bridge/CHANGELOG.md, packages/electron-bridge/package.json, packages/electron-log/CHANGELOG.md, packages/electron-log/package.json, packages/electron-plugin/CHANGELOG.md, packages/electron-plugin/package.json, packages/electron-runtime/CHANGELOG.md, packages/electron-runtime/package.json, packages/electron-test/CHANGELOG.md, packages/electron-test/package.json, packages/electron-tools/CHANGELOG.md, packages/electron-tools/package.json, packages/electron-tools/src/dev/index.ts
when start main process in dev, do not exist if tsc with errors.
=> Fix dev tsc

pnpm-lock.yaml
=> feat: update pnpm-lock.yml

.gitignore, packages/electron-bridge/CHANGELOG.md, packages/electron-bridge/package.json, packages/electron-log/CHANGELOG.md, packages/electron-log/package.json, packages/electron-plugin/CHANGELOG.md, packages/electron-plugin/package.json, packages/electron-plugin/src/dev.ts, packages/electron-runtime/CHANGELOG.md, packages/electron-runtime/package.json, packages/electron-test/CHANGELOG.md, packages/electron-test/package.json, packages/electron-tools/CHANGELOG.md, packages/electron-tools/package.json, packages/electron-tools/src/pack/builder-config.ts
- Fix Windows compatibility issues
=> Fix: Windows compatibility issues

apps/modern-electron-example/CHANGELOG.md, apps/modern-electron-example/package.json, packages/electron-bridge/CHANGELOG.md, packages/electron-bridge/package.json, packages/electron-log/CHANGELOG.md, packages/electron-log/package.json, packages/electron-plugin/CHANGELOG.md, packages/electron-plugin/package.json, packages/electron-runtime/CHANGELOG.md, packages/electron-runtime/package.json, packages/electron-test/CHANGELOG.md, packages/electron-test/package.json, packages/electron-tools/CHANGELOG.md, packages/electron-tools/package.json
- support electron 14
- support @electron/remote@^2
=> feat: publish v2.0.0

.github/workflows/ci.yml, .github/workflows/release.yml, apps/modern-electron-example/electron/main.ts, packages/electron-runtime/src/services/lifecycle/common/lifecycle.ts, packages/electron-runtime/src/services/lifecycle/electron-main/lifecycle.ts, packages/electron-runtime/src/services/update/electron-render/IUpdate.ts, packages/electron-tools/cli.js
- fix updateService type error.
- fix electron-tools build env: set NODE_NEV default value: production.
- add cli yml
- add getForceQuit api
=> Fix some errors

.github/workflows/ci.yml, .github/workflows/release.yml, apps/modern-electron-example/electron/main.ts, packages/electron-runtime/src/services/lifecycle/common/lifecycle.ts, packages/electron-runtime/src/services/lifecycle/electron-main/lifecycle.ts, packages/electron-runtime/src/services/update/electron-render/IUpdate.ts, packages/electron-tools/cli.js
* fix: checkUpdate type error
* feat: add ci
* feat: add getForceQuit api
* fix: tools build env
=> Fix some errors (#35)

apps/modern-electron-example/CHANGELOG.md, apps/modern-electron-example/package.json, packages/electron-bridge/CHANGELOG.md, packages/electron-bridge/package.json, packages/electron-log/CHANGELOG.md, packages/electron-log/package.json, packages/electron-plugin/CHANGELOG.md, packages/electron-plugin/package.json, packages/electron-runtime/CHANGELOG.md, packages/electron-runtime/package.json, packages/electron-test/CHANGELOG.md, packages/electron-test/package.json, packages/electron-tools/CHANGELOG.md, packages/electron-tools/package.json
- support shared folder compile
=> feat: publish v2.0.3

apps/modern-electron-example/CHANGELOG.md, apps/modern-electron-example/package.json, packages/electron-bridge/CHANGELOG.md, packages/electron-bridge/package.json, packages/electron-log/CHANGELOG.md, packages/electron-log/package.json, packages/electron-plugin/CHANGELOG.md, packages/electron-plugin/package.json, packages/electron-runtime/CHANGELOG.md, packages/electron-runtime/package.json, packages/electron-test/CHANGELOG.md, packages/electron-test/package.json, packages/electron-tools/CHANGELOG.md, packages/electron-tools/package.json
- support shared folder compile
=> feat: publish v1.0.5

packages/electron-tools/src/pack/pack.ts
=> fix: linuxArm64 pack

packages/electron-plugin/src/plugin-config.ts, packages/electron-tools/src/pack/pack.ts
=> fix: linux pack

apps/modern-electron-example/CHANGELOG.md, apps/modern-electron-example/package.json, packages/electron-bridge/CHANGELOG.md, packages/electron-bridge/package.json, packages/electron-log/CHANGELOG.md, packages/electron-log/package.json, packages/electron-plugin/CHANGELOG.md, packages/electron-plugin/package.json, packages/electron-runtime/CHANGELOG.md, packages/electron-runtime/package.json, packages/electron-test/CHANGELOG.md, packages/electron-test/package.json, packages/electron-tools/CHANGELOG.md, packages/electron-tools/package.json
=> feat: publish v2.0.4

apps/modern-electron-example/CHANGELOG.md, apps/modern-electron-example/package.json, packages/electron-bridge/CHANGELOG.md, packages/electron-bridge/package.json, packages/electron-log/CHANGELOG.md, packages/electron-log/package.json, packages/electron-plugin/CHANGELOG.md, packages/electron-plugin/package.json, packages/electron-runtime/CHANGELOG.md, packages/electron-runtime/package.json, packages/electron-test/CHANGELOG.md, packages/electron-test/package.json, packages/electron-tools/CHANGELOG.md, packages/electron-tools/package.json
=> feat: publish v1.0.6

.github/workflows/ci.yml, apps/modern-electron-example/CHANGELOG.md, apps/modern-electron-example/package.json, packages/electron-bridge/CHANGELOG.md, packages/electron-bridge/package.json, packages/electron-log/CHANGELOG.md, packages/electron-log/package.json, packages/electron-plugin/CHANGELOG.md, packages/electron-plugin/package.json, packages/electron-runtime/CHANGELOG.md, packages/electron-runtime/package.json, packages/electron-test/CHANGELOG.md, packages/electron-test/package.json, packages/electron-tools/CHANGELOG.md, packages/electron-tools/package.json
publish v1.0.7
- fix lifecycle service ipc problem
- fix linux pack problem
=> feat: publish v1.0.7

apps/modern-electron-example/CHANGELOG.md, apps/modern-electron-example/package.json, packages/electron-bridge/CHANGELOG.md, packages/electron-bridge/package.json, packages/electron-log/CHANGELOG.md, packages/electron-log/package.json, packages/electron-plugin/CHANGELOG.md, packages/electron-plugin/package.json, packages/electron-runtime/CHANGELOG.md, packages/electron-runtime/package.json, packages/electron-test/CHANGELOG.md, packages/electron-test/package.json, packages/electron-tools/CHANGELOG.md, packages/electron-tools/package.json
- support webpack4 import way.
=> feat: support webpack4

packages/electron-runtime/src/services/lifecycle/electron-render/lifecycle.ts, packages/electron-runtime/src/services/update/electron-render/update.ts
- fix checkUpdate params problem.
=> Fix upgrade

packages/electron-runtime/src/preload/winService.ts, packages/electron-runtime/src/services/windows/electron-render/IWindows.ts
=> feat: support winservice.windowId api (#71)

package.json, packages/electron-runtime/package.json
set electron-updater as peerDependencies
=> set electron-updater as peerDependencies

packages/electron-tools/src/babel-plugin/replace-jupiter-pkg-name.ts, packages/electron-tools/src/config/babel-config.ts, packages/electron-tools/src/utils/project.ts
=> feat: support jupiter plugin

package.json
reference:https://github.com/WarnerHooh/babel-plugin-parameter-decorator/issues/34
=> fix: electron-runtime compile error

apps/modern-electron-example/CHANGELOG.md, apps/modern-electron-example/package.json, packages/electron-bridge/CHANGELOG.md, packages/electron-bridge/package.json, packages/electron-log/CHANGELOG.md, packages/electron-log/package.json, packages/electron-plugin/CHANGELOG.md, packages/electron-plugin/package.json, packages/electron-runtime/CHANGELOG.md, packages/electron-runtime/package.json, packages/electron-test/CHANGELOG.md, packages/electron-test/package.json, packages/electron-tools/CHANGELOG.md, packages/electron-tools/package.json
- change "sync shell env " to optional.
=> feat: publish for v1.0.16

monorepo.code-workspace, package.json, packages/electron-plugin/package.json, packages/electron-plugin/src/get-config-by-build-mode.ts, packages/electron-plugin/src/index.ts, packages/electron-runtime/src/main.ts
- fix runtime compile error
- set "syncShellEnv" as option
=> feat: improve plugin

packages/electron-runtime/src/interfaces/common.ts, packages/electron-runtime/src/main.ts
- add "fixDotNetVersion?: boolean; " as start option
=> feat: improve start time

packages/electron-runtime/src/interfaces/common.ts, packages/electron-runtime/src/main.ts
=> feat: improve start time (#97)

.github/workflows/ci.yml, packages/electron-runtime/src/services/lifecycle/electron-main/lifecycle.ts
use settimeout is to hack, use the suggestion in issue of the official repo !
see:  https://github.com/electron/electron/issues/33643
=> fix: app not quit while call app.quit() twice in the quit callback

.changeset/silent-kids-pull.md, apps/modern-electron-example/CHANGELOG.md, apps/modern-electron-example/package.json, packages/electron-tools/CHANGELOG.md, packages/electron-tools/package.json, packages/electron-tools/src/babel-plugin/replace-pkg-name.ts
- fix: remove unnecessary console.log calls
=> chore: v2.0.18
